# Generated by Django 3.2.13 on 2022-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ric_code', models.CharField(max_length=50)),
                ('esg_score', models.IntegerField(blank=True, null=True)),
                ('environment_score', models.IntegerField(blank=True, null=True)),
                ('social_score', models.IntegerField(blank=True, null=True)),
                ('governance_score', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
